version: "3.8"

services:
  flask-backend:
    build:
      context: ./backend/src  
      dockerfile: DockerFile
    container_name: flask-backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend/src:/app 
      - ./backend/data:/app/data  
      - ./entity_relationship_extraction:/app/entity_relationship_extraction
    environment:
      - NEO4J_URI=neo4j+s://6b5f0965.databases.neo4j.io
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=SqxvGpasJ9eEAt6-kBaKYskFQnhxmsk0QOY8i1nsnik
      - OPENAI_API_KEY=<INSERT API KEY HERE>
      - GOOGLE_API_KEY=AIzaSyACdvWDLdk00vEvtLn_T2H5mX8NAMz-w3M
    networks:
      - mynetwork

  react-frontend:
    build:
      context: ./frontend  
      dockerfile: DockerFile
    container_name: react-frontend
    ports:
      - "3000:3000"  
    depends_on:
      - flask-backend 

networks:
  mynetwork:
    driver: bridge